### ISSUE TITLE
Bom Submission

### ISSUE THREAD

**Issue by timChase98** [cwg19/Function-Generator#1]
- [x] All values should be in engineering notation 
- [x] Rating and Tolerance columns in the wrong spot 
- [x] NA should be empty cells

Please check off the issues as you fix them. When you are done push your changes, create a new release, and close the issue with a comment that @s me. I'll review your changes and mark you as good to order parts or I'll open a new issue if you need to make changes.

**Comment by cwg19** [comment]
Hey Tim,

Thanks for the feedback, I'll get right on those changes.

Stupid question: when you say values must be in engineering notation, what do you mean? As in write 1.3k instead of 1k3 for a 1.3k ohm resistor?

Thank you,
Chris Gravelle
________________________________

**Comment by timChase98** [comment]
https://en.wikipedia.org/wiki/Engineering_notation

**Comment by cwg19** [comment]
I think its fixed @timChase98

**Comment by timChase98** [comment]
- [ ] Engineering notation on line 2 and 3
- [ ] Add me as an owner

**Comment by cwg19** [comment]
Did you want line 2 and 3 in nF? that is what I changed cus idk.

I invited you as a collaborator.
________________________________

**Comment by timChase98** [comment]
Yes that's what I was referring to
