### ISSUE TITLE
Schematic Submission 

### ISSUE THREAD

**Issue by timChase98** [cwg19/Function-Generator#2]
- [x] All project files should be under version control 
- [x] This could use some more organization, consider rearranging to make signal flow clear or moving to multiple pages.  I think multiple pages would be better
  - [x] Power input top left
  - [x] Inputs to uController middle left 
  - [ ] uController in the center
  - [x] uController outputs to right  
- [x] Component designators and values should be neat and readable 
- [x] Where did you find the schematic to generate the negative rail? 

Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by cwg19** [comment]
Uploading schematic and board files as I edit them and make revisions. I organized the Schematic into 3 sheets, the first is power components, the second is the signal generator / amplification and output, and the third sheet is my uController with I/O components. The component designators are neat and readable on the schematic. I am hopeless on the board layout as it is very crowded. The schematic to generate +- 12V is in my data sheets folder called plusminus12v.pdf

**Comment by timChase98** [comment]
- [x] I still don't see your eagle files in the repo
- [x] It looks like you should add a 100nF cap across the power pins of the oscillator, also what is the purpose of the OE pin? 
- [x] If you are using an OLED display you need to use logic level converters.  If not ignore this 

Fix these things and you'll get a PASS

**Comment by cwg19** [comment]
I put the .brd and .sch files in the Eagle directory. Do you want the whole project dumped in there?
I will insert the 100nF cap across the power pins of the oscillator and update my project files. The OE pin, I believe, is the "output enable" pin. When it is pulled high or left NC, then the oscillator is enabled; pulled to GND and the oscillator is off.
I am not using an OLED, so I will ignore.

**Comment by timChase98** [comment]
Either is fine.  Move them to the base directory.  Close this when you want me to look them over

**Comment by cwg19** [comment]
Fixed the bullet points. Please let me know if there are other issues which need to be adjusted. Thank you!
