### ISSUE TITLE
Board Submission

### ISSUE THREAD

**Issue by timChase98** [cwg19/Function-Generator#3]
Did you intend to use through hole diodes? If not you should be able to replace them with SMA without making major changes to your layout.  This otherwise looks good, there are a couple of spots where you made some weird routing choices but this is far from bad.  Also a pin one marker on the programming header would be a great idea.

**Comment by cwg19** [comment]
The through hole diodes are a mistake. I will replace it with SMA diodes.
Just out of curiosity, where were some of the weirder or more questionable routings made? I get a strong sense that my component layout isn't very efficient or logical.

**Comment by timChase98** [comment]
Component placement is the most important part of routing.  You also have some long windy traces that could have been straight or split into a Y.  The trace that goes through the cathode of D1 is an example of this.  The trace from pin3 on IC4 to the pot header is also like this.  Pin3 on the 1k pot is also like this.  None of these are show stoppers but when in doubt minimize loop area.

**Comment by cwg19** [comment]
Noted, thank you. Realistically, I will not be able to layout and route my board again in time. Is it manufacturable as is, or are there further issues that need fixing as far as you can tell?

**Comment by timChase98** [comment]
I believe it is.  I'll mark it as a pass.

**Comment by timChase98** [comment]
Your board was sent to fab.  You probably knew this already though
